### ISSUE TITLE
meta_info

### ISSUE THREAD

**Issue by omarirfa** [liuyuan-pal/Gen6D#7]
Hi,

I was trying to make my own custom object to track and was following your tutorial. I have two questions:

1. In your mouse-ref file, you had a mouse on an ArUco board. Do I need an ArUco board as well when I am recording my custom object? If yes, can I just use any ArUco board online for this purpose?
2. I am confused on how to to get the meta_info using CloudCompare. It says to get the x+ and z+ direction from the plane point cloud? I was wondering how do you find those since I do not see those values in the image. Is that value in the properties or console of CloudCompare?

Image for ref: 
![explain3](https://user-images.githubusercontent.com/61637151/180113825-f42aee4d-9d71-40bc-990d-c75826f56bff.png)

**Comment by liuyuan-pal** [comment]
Hi,
1. You don't need the same board but you need to ensure the background contains enough textures so that COLMAP is able to recover all camera poses accurately.
2. I fit a plane on a cropped region and use its normal as the Z+ direction for the object:
1) I first cropped a point cloud like the following
![0](https://user-images.githubusercontent.com/23974453/180131088-2276321d-cf02-4fca-9929-774bb3de1e6f.png)
2) Then, I fit a plane on this point cloud
![1](https://user-images.githubusercontent.com/23974453/180131161-a9f735cf-ea5a-4a2d-834c-c376d8764b1c.png)
3) Finally, I visualize the normal and use the normal as the Z direction
![2](https://user-images.githubusercontent.com/23974453/180131205-b0ecd8d5-de96-4a15-aafe-b07a9857ec54.png)
The normal is shown in the left-bottom panel. Note that the normal is opposite to the Z+ direction (up), so the Z+ direction for the object is (-0.04148,-0.13305,-0.99024)
4) To get the forward direction (x+) of the object, we use the point picking tool to pick a direction
![3](https://user-images.githubusercontent.com/23974453/180131612-9449d1be-33b8-4c68-8777-eec6cd7633b5.png)
Then, the forward direction for this object is (-0.1606,-0.8393,0.1194).

**Comment by omarirfa** [comment]
Thank you for the explanation! I was able to make the meta_info file successfully. After running the code on the test video, I noticed that the bounding box has not covered the object in the video. I had a few questions for this:

1. Is this the same issue as #4 where you said to downsample the image? How would I downsample the test video? by opencv?   
2. In the images_inter, there is a column of images where it shows the images it references, I was wondering if it matters that the reference-video is that small? since I was comparing to the mouse_processed ones and you had a completely bigger picture for the mouse in that column. Please refer to the circled part in images_inter. I have added the mouse_images_inter for reference.

Images_inter:
![0](https://user-images.githubusercontent.com/61637151/180587837-2b38c3f8-bff9-4b12-af0d-5f97e58a4cba.jpg)

Mouse_images_inter:
![0](https://user-images.githubusercontent.com/61637151/180587892-0756f662-acaf-4cea-9bdc-461a2fe8c44d.jpg)

**Comment by liuyuan-pal** [comment]
Hi, the reference images are too small in your case. Because the reference images are scaled according to the `object_point_cloud.ply`. Current codes will offset the `object_point_cloud.ply` to the origin and scale it into a unit sphere. Then, all reference images will be resized to compactly include the projection of the unit sphere as stated in Section 2 of the supplementary material. In this case, if the cropped `object_point_cloud.ply` is more compact, the image of the object will be larger. Thus, the image matching of Gen6D will be more accurate for the pose prediction.

**Comment by AmokraneIlhem** [comment]
> Hi,
> 
> 1. You don't need the same board but you need to ensure the background contains enough textures so that COLMAP is able to recover all camera poses accurately.
> 2. I fit a plane on a cropped region and use its normal as the Z+ direction for the object:
> 
> 1. I first cropped a point cloud like the following
>    ![0](https://user-images.githubusercontent.com/23974453/180131088-2276321d-cf02-4fca-9929-774bb3de1e6f.png)
> 2. Then, I fit a plane on this point cloud
>    ![1](https://user-images.githubusercontent.com/23974453/180131161-a9f735cf-ea5a-4a2d-834c-c376d8764b1c.png)
> 3. Finally, I visualize the normal and use the normal as the Z direction
>    ![2](https://user-images.githubusercontent.com/23974453/180131205-b0ecd8d5-de96-4a15-aafe-b07a9857ec54.png)
>    The normal is shown in the left-bottom panel. Note that the normal is opposite to the Z+ direction (up), so the Z+ direction for the object is (-0.04148,-0.13305,-0.99024)
> 4. To get the forward direction (x+) of the object, we use the point picking tool to pick a direction
>    ![3](https://user-images.githubusercontent.com/23974453/180131612-9449d1be-33b8-4c68-8777-eec6cd7633b5.png)
>    Then, the forward direction for this object is (-0.1606,-0.8393,0.1194).

Hi,
the cropped point cloud in the first capture where it comes from , please?

**Comment by liuyuan-pal** [comment]
Hi, just like you crop the point cloud for the object. You crop a subset of the point cloud of the calibration board and fit the plane on the cropped subset.
